version: '2'

services:

  redis:
    image: 'bitnami/redis:latest'
    ports:
      - 6379:6379
    volumes:
      - /Users/cristian.oliveira/.redis:/bitnami/redis

  postgresql:
    image: postgres:9.5
    environment:
      POSTGRES_USER: "afg"
      POSTGRES_PASSWORD: "afg"
    ports:
      - 5432:5432
